### ISSUE TITLE
Installation of full version (parrot_arsdk missing)

### ISSUE THREAD

**Issue by ghost** [aerostack/install#1]
Hello, 
I was using the previous version of Aerostack and now I'm trying to install the full project on Ubuntu 20 + ROS Noetic.
However, my installation fails due to the absence of the parrot_arsdk in ROS Noetic.
I've tried to install the package from source, but it also isn't installing that way.

What would you suggest? Any solution for this package? I won't need Parrot hardware interfaces, but I'm interested in looking at and testing all the new functionalities.

Thank you!

**Comment by miferco97** [comment]
Hi AndreM-rbtcs,

Indeed, the  the parrot_arsdk dependency is obsolete and should be removed from the aerostack packages.
Which is the step that gives you problems due to this package? If its only during the setup_dependencies step , try to build aerostack workspace without this package. Otherwise, more information about this error would be really useful for fixing this error. 

Thanks for letting us know this issue.

**Comment by ghost** [comment]
Thank you for your reply, @miferco97. I think I have now managed to skip this error by commenting the lines associated with the bebop2 interface in the full_aerostack.repos file.
Still, I can't successfully build all the packages, now due to OpenCV version errors. Do you want me to open a new issue about this other problem?

Has anyone successfully installed and built the full framework on a new installation? I've tried in 3 different machines with new Ubuntu 20.04 LTS + ROS Noetic full installations and haven't yet been successful.

**Comment by miferco97** [comment]
Hi @AndreM-rbtcs, thanks for showing us how you tackle this problem. We will handle it ASAP.
Furthermore, I would be pleased if you open a new issue for the OpenCV problems, try to add all the information of this errors, facilitating our answer. 
We have tested the full installation before the new release, but we will test it again in a clean machine to find new installation errors.
Thank you again for posting this issues.
